baseURL = "https://ruedelamadeleine.be/"
languageCode = "en-us"
title = "rue de la madeleine"
disableKinds = ["taxonomy", "taxonomyTerm", "RSS"]

[params]
  author = "Clara Noirhomme"
  description = "handmade apparel confectioned in Liège"

[markup.goldmark.renderer]
unsafe= true